name: ghcjs-test-client
executables:
  ghcjs-test-client:
    main: Main.hs
    source-dirs:
      - ./.
    dependencies:
      - base
      - reflex-dom
      - containers
      - safe
      - generics-eot
